---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver-provider-pulumi-esc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/version: "0.4.2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-provider-pulumi-esc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/version: "0.4.2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-provider-pulumi-esc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/version: "0.4.2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-store-csi-driver-provider-pulumi-esc
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: secrets-store-csi-driver-provider-pulumi-esc
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secrets-store-csi-driver-provider-pulumi-esc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
    app.kubernetes.io/version: "0.4.2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
      app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secrets-store-csi-driver-provider-pulumi-esc
        app.kubernetes.io/instance: secrets-store-csi-driver-provider-pulumi-esc
        app.kubernetes.io/version: "0.4.2"
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      serviceAccountName: secrets-store-csi-driver-provider-pulumi-esc

      containers:
      - name: secrets-store-csi-driver-provider-pulumi-esc
        image: ghcr.io/pulumi/pulumi-esc-csi-provider
        imagePullPolicy: Always
        resources:
          {}
        args:
        - "-endpoint=/provider/pulumi.sock"
        volumeMounts:
        - name: socket
          mountPath: /provider
      volumes:
      - name: socket
        hostPath:
          path: /etc/kubernetes/secrets-store-csi-providers
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
